sudo: required
services:
    - docker
before-install:
    - docker build -t lokialice/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lokialice/docker-react npm run test -- --coverage